### PR TITLE
Account inventory nullability and item types without descriptions

### PR DESCRIPTION
**Pull request by Sheldan**
These issues were found after checking some items, so I added them.
Additionally, shared inventory slots can be nullable.

### CODE REVIEW

**Comment by Kryszak** [comment]
First of all, thanks for double-checking and fixing bugs in functionality.
PR looks good, just one request - bump project version to `1.9.5` so it'll be ready for release after merge.

**Comment by Sheldan** [comment]
@Kryszak I thought I could release this on my own, but it seems I have failed terribly. 
I created the tage and release manually which then triggered the release pipeline. It seems the error was that the release _is created by the pipeline_. I deleted the release (or rather it was gone) and a retry of the pipeline seems to have failed, because an earlier step already performed an action that was not undone.

**Comment by Kryszak** [comment]
Yup, manual creation of release on Github broke the whole pipeline.
One would think that it should just do nothing in case matching release already exists.
For know I'll put an issue for that and push the documentation.
You can recreate github release manually as rerunning pipeline will fail all the time now since maven central release already exists @Sheldan

**Comment by Sheldan** [comment]
I will recreate the Github release, and everything else was performed?

**Comment by Kryszak** [comment]
The documentation for new version was manually pushed, I'm now looking at not failing the whole pipeline on existing github release.

**Comment by Sheldan** [comment]
I could fetch the version from maven central.
Sorry again for the issues I have caused.

**Pull request merged**
